{
 "title": "EODAG",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PRODUCT_TYPES_TARGET", "query": "67" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Timeseries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active requests over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(eodag_otelcol_exporter_http_server_active_requests)"
    }
   ]
  },
  {
   "title": "Requests overhead over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(eodag_otelcol_exporter_eodag_server_request_overhead_duration_seconds_bucket[1h])) by (le) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repartition of request duration over time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(\n  increase(eodag_otelcol_exporter_eodag_server_request_duration_seconds_bucket[$__interval])\n  )\nby (le)\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Available providers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(eodag_otelcol_exporter_eodag_core_available_providers))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "List of available providers",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "max(eodag_otelcol_exporter_eodag_core_available_providers) by (provider_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available product types (% of target)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum((eodag_otelcol_exporter_eodag_core_available_product_types / $PRODUCT_TYPES_TARGET) * 100))"
    }
   ]
  },
  {
   "title": "List of available datasets",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 23 },
   "targets": [
    {
     "expr": "max(eodag_otelcol_exporter_eodag_core_available_product_types) by (product_type_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Data downloaded per provider",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(eodag_otelcol_exporter_eodag_download_downloaded_data_bytes_total) by (provider)"
    }
   ]
  },
  {
   "title": "Requested product types (Top 10)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 15, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, max(eodag_otelcol_exporter_eodag_core_searched_product_types_total) by (product_type))"
    }
   ]
  }
 ]
}